[package]
name = "voxora"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Deterministic 3D Video Projection in Pure Rust"

[lints]
workspace = true

[dependencies]
voxora-core = { path = "../voxora-core", version = "0.1.0" }
voxora-geometry = { path = "../voxora-geometry", version = "0.1.0" }
voxora-math = { path = "../voxora-math", version = "0.1.0" }
voxora-reconstruction = { path = "../voxora-reconstruction", version = "0.1.0" }
voxora-render = { path = "../voxora-render", version = "0.1.0" }
voxora-vision = { path = "../voxora-vision", version = "0.1.0" }
